### ISSUE TITLE
We need to recalculate the nearest sensor when we update the AQI

### ISSUE THREAD

**Issue by obra** [skalnik/aqi-wtf#29]
I had the app up while driving home today. Without a browser refresh, the app continued to show the AQI at my starting location, even though it updated every minute.

**Comment by skalnik** [comment]
I dig this idea. I think it'd definitely blow the rate limit regularly unless we pair this with https://github.com/skalnik/aqi-wtf/issues/22.

**Comment by obra** [comment]
I don't see why it would. We don't have to throw away the sensors list while it's in memory.

**Comment by skalnik** [comment]
> I don't see why it would. We don't have to throw away the sensors list while it's in memory.

Ah that's true, as long as we keep the list around it should be fine!
