### ISSUE TITLE
Make error page a bit more useful

### ISSUE THREAD

**Issue by obra** [skalnik/aqi-wtf#31]
By the time we've gotten to the error page, we almost always have a lat/lon. We could at least throw a link to the purpleair map there.

**Comment by skalnik** [comment]
Hm, I guess #34 really addressed https://github.com/skalnik/aqi-wtf/issues/32 more than this. Reopening for tracking to do some more useful action if we get an error.

**Comment by skalnik** [comment]
Another idea floated by @sshirokov last night is to just regularly try again. Usually the errors resolve themselves pretty quickly, or it's a rate limit that goes away with time. Just continuing to try to refetch the data every second or so (or maybe exponential back off) could go a long way to resolving this.

**Comment by obra** [comment]
I would strongly caution against deploying -without- exponential backoff. But yeah, retrying makes sense. As might clearing the locally stored state if: 

1) The error was not a rate-limit error
2) we have failed some number of times in a row.

But we're going to end up with errors not related to connectivity blips and forcing reloads in those cases may just cause more trouble.
