### ISSUE TITLE
on iOS when launched from homescreen, the credits are covered by system UI

### ISSUE THREAD

**Issue by obra** [skalnik/aqi-wtf#33]
We might want to add an em of padding underneath or something.

![image](https://user-images.githubusercontent.com/45416/92425948-85e68e80-f13d-11ea-8072-69108a9bc28f.png)

**Comment by skalnik** [comment]
https://css-tricks.com/the-notch-and-css/ is a helpful reference here. I'll see if I can dig into this over lunch.

**Comment by skalnik** [comment]
Bah, I forgot I was fixing this in #44 and didn't actually double check. Doesn't seem I fixed it 😓
