### ISSUE TITLE
Claim that geolocation "never leaves your device" appears inaccurate.

### ISSUE THREAD

**Issue by mkruisselbrink** [skalnik/aqi-wtf#72]
Looking at the source code, it appears the geolocation is send to purpleair.com, making the claim that it never leaves your device rather deceiving.
At the very least it seems to code could try to round to whole degrees or something to not upload the exact location. But even then the current claim would still be wrong.

**Comment by skalnik** [comment]
Ah you're right, since we implemented the geofenced grab of sensors PurpleAir gets an idea of your location. I'll go ahead and remove that so we can keep this claim. Thanks for pointing this out.
